// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1g7ovOio91YlWqJZW36fivL03TNdeb7U',
    appId: '1:958646803847:web:519a03e892442339534722',
    messagingSenderId: '958646803847',
    projectId: 'glsib-a3f40',
    authDomain: 'glsib-a3f40.firebaseapp.com',
    storageBucket: 'glsib-a3f40.firebasestorage.app',
    measurementId: 'G-0XH65404Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTPHBwQ3UAIBDlqDmLoV8CRGeJsZkh7Eg',
    appId: '1:958646803847:android:25069fa39abac49e534722',
    messagingSenderId: '958646803847',
    projectId: 'glsib-a3f40',
    storageBucket: 'glsib-a3f40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd5axPf0zR07nJQgD1pdoT4ZH8Qf7wv9g',
    appId: '1:958646803847:ios:b9c0defc9357069d534722',
    messagingSenderId: '958646803847',
    projectId: 'glsib-a3f40',
    storageBucket: 'glsib-a3f40.firebasestorage.app',
    iosBundleId: 'com.example.forumExperience',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd5axPf0zR07nJQgD1pdoT4ZH8Qf7wv9g',
    appId: '1:958646803847:ios:b9c0defc9357069d534722',
    messagingSenderId: '958646803847',
    projectId: 'glsib-a3f40',
    storageBucket: 'glsib-a3f40.firebasestorage.app',
    iosBundleId: 'com.example.forumExperience',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1g7ovOio91YlWqJZW36fivL03TNdeb7U',
    appId: '1:958646803847:web:d819c9427460243f534722',
    messagingSenderId: '958646803847',
    projectId: 'glsib-a3f40',
    authDomain: 'glsib-a3f40.firebaseapp.com',
    storageBucket: 'glsib-a3f40.firebasestorage.app',
    measurementId: 'G-5X8GZ868DT',
  );

}